
using System.Collections.Generic;

namespace Miljokaz.Models
{
	public class ColorsList
	{
		public string ColorName { get; set; }
		public string ColorHexCode { get; set; }
		public int Status { get; set; }
		public string? CategoryName { get; set; }

	}

	public static class MyColors
	{
		public static List<ColorsList> ColorList { get; private set; }

		static MyColors()
		{
			ColorList = new List<ColorsList>
		{
			new ColorsList { ColorName = "aliceblue", ColorHexCode = "#F0F8FF", Status = 0 },
			new ColorsList { ColorName = "antiquewhite", ColorHexCode = "#FAEBD7", Status = 0 },
			new ColorsList { ColorName = "aqua", ColorHexCode = "#00FFFF", Status = 0 },
			new ColorsList { ColorName = "aquamarine", ColorHexCode = "#7FFFD4", Status = 0 },
			new ColorsList { ColorName = "azure", ColorHexCode = "#F0FFFF", Status = 0 },
			new ColorsList { ColorName = "beige", ColorHexCode = "#F5F5DC", Status = 0 },
			new ColorsList { ColorName = "bisque", ColorHexCode = "#FFE4C4", Status = 0 },
			new ColorsList { ColorName = "black", ColorHexCode = "#000000", Status = 0 },
			new ColorsList { ColorName = "blanchedalmond", ColorHexCode = "#FFEBCD", Status = 0 },
			new ColorsList { ColorName = "blue", ColorHexCode = "#0000FF", Status = 0 },
			new ColorsList { ColorName = "blueviolet", ColorHexCode = "#8A2BE2", Status = 0 },
			new ColorsList { ColorName = "brown", ColorHexCode = "#A52A2A", Status = 0 },
			new ColorsList { ColorName = "burlywood", ColorHexCode = "#DEB887", Status = 0 },
			new ColorsList { ColorName = "cadetblue", ColorHexCode = "#5F9EA0", Status = 0 },
			new ColorsList { ColorName = "chartreuse", ColorHexCode = "#7FFF00", Status = 0 },
			new ColorsList { ColorName = "chocolate", ColorHexCode = "#D2691E", Status = 0 },
			new ColorsList { ColorName = "coral", ColorHexCode = "#FF7F50", Status = 0 },
			new ColorsList { ColorName = "cornflowerblue", ColorHexCode = "#6495ED", Status = 0 },
			new ColorsList { ColorName = "cornsilk", ColorHexCode = "#FFF8DC", Status = 0 },
			new ColorsList { ColorName = "crimson", ColorHexCode = "#DC143C", Status = 0 },
			new ColorsList { ColorName = "cyan", ColorHexCode = "#00FFFF", Status = 0 },
			new ColorsList { ColorName = "darkblue", ColorHexCode = "#00008B", Status = 0 },
			new ColorsList { ColorName = "darkcyan", ColorHexCode = "#008B8B", Status = 0 },
			new ColorsList { ColorName = "darkgoldenrod", ColorHexCode = "#B8860B", Status = 0 },
			new ColorsList { ColorName = "darkgray", ColorHexCode = "#A9A9A9", Status = 0 },
			new ColorsList { ColorName = "darkgreen", ColorHexCode = "#006400", Status = 0 },
			new ColorsList { ColorName = "darkkhaki", ColorHexCode = "#BDB76B", Status = 0 },
			new ColorsList { ColorName = "darkmagenta", ColorHexCode = "#8B008B", Status = 0 },
			new ColorsList { ColorName = "darkolivegreen", ColorHexCode = "#556B2F", Status = 0 },
			new ColorsList { ColorName = "darkorange", ColorHexCode = "#FF8C00", Status = 0 },
			new ColorsList { ColorName = "darkorchid", ColorHexCode = "#9932CC", Status = 0 },
			new ColorsList { ColorName = "darkred", ColorHexCode = "#8B0000", Status = 0 },
			new ColorsList { ColorName = "darksalmon", ColorHexCode = "#E9967A", Status = 0 },
			new ColorsList { ColorName = "darkseagreen", ColorHexCode = "#8FBC8B", Status = 0 },
			new ColorsList { ColorName = "darkslateblue", ColorHexCode = "#483D8B", Status = 0 },
			new ColorsList { ColorName = "darkslategray", ColorHexCode = "#2F4F4F", Status = 0 },
			new ColorsList { ColorName = "darkturquoise", ColorHexCode = "#00CED1", Status = 0 },
			new ColorsList { ColorName = "darkviolet", ColorHexCode = "#9400D3", Status = 0 },
			new ColorsList { ColorName = "deeppink", ColorHexCode = "#FF1493", Status = 0 },
			new ColorsList { ColorName = "deepskyblue", ColorHexCode = "#00BFFF", Status = 0 },
			new ColorsList { ColorName = "dimgray", ColorHexCode = "#696969", Status = 0 },
			new ColorsList { ColorName = "dodgerblue", ColorHexCode = "#1E90FF", Status = 0 },
			new ColorsList { ColorName = "firebrick", ColorHexCode = "#B22222", Status = 0 },
			new ColorsList { ColorName = "floralwhite", ColorHexCode = "#FFFAF0", Status = 0 },
			new ColorsList { ColorName = "forestgreen", ColorHexCode = "#228B22", Status = 0 },
			new ColorsList { ColorName = "fuchsia", ColorHexCode = "#FF00FF", Status = 0 },
			new ColorsList { ColorName = "gainsboro", ColorHexCode = "#DCDCDC", Status = 0 },
			new ColorsList { ColorName = "ghostwhite", ColorHexCode = "#F8F8FF", Status = 0 },
			new ColorsList { ColorName = "gold", ColorHexCode = "#FFD700", Status = 0 },
			new ColorsList { ColorName = "goldenrod", ColorHexCode = "#DAA520", Status = 0 },
			new ColorsList { ColorName = "gray", ColorHexCode = "#808080", Status = 0 },
			new ColorsList { ColorName = "green", ColorHexCode = "#008000", Status = 0 },
			new ColorsList { ColorName = "greenyellow", ColorHexCode = "#ADFF2F", Status = 0 },
			new ColorsList { ColorName = "honeydew", ColorHexCode = "#F0FFF0", Status = 0 },
			new ColorsList { ColorName = "hotpink", ColorHexCode = "#FF69B4", Status = 0 },
			new ColorsList { ColorName = "indianred", ColorHexCode = "#CD5C5C", Status = 0 },
			new ColorsList { ColorName = "indigo", ColorHexCode = "#4B0082", Status = 0 },
			new ColorsList { ColorName = "ivory", ColorHexCode = "#FFFFF0", Status = 0 },
			new ColorsList { ColorName = "khaki", ColorHexCode = "#F0E68C", Status = 0 },
			new ColorsList { ColorName = "lavender", ColorHexCode = "#E6E6FA", Status = 0 },
			new ColorsList { ColorName = "lavenderblush", ColorHexCode = "#FFF0F5", Status = 0 },
			new ColorsList { ColorName = "lawngreen", ColorHexCode = "#7CFC00", Status = 0 },
			new ColorsList { ColorName = "lemonchiffon", ColorHexCode = "#FFFACD", Status = 0 },
			new ColorsList { ColorName = "lightblue", ColorHexCode = "#ADD8E6", Status = 0 },
			new ColorsList { ColorName = "lightcoral", ColorHexCode = "#F08080", Status = 0 },
			new ColorsList { ColorName = "lightcyan", ColorHexCode = "#E0FFFF", Status = 0 },
			new ColorsList { ColorName = "lightgoldenrodyellow", ColorHexCode = "#FAFAD2", Status = 0 },
			new ColorsList { ColorName = "lightgray", ColorHexCode = "#D3D3D3", Status = 0 },
			new ColorsList { ColorName = "lightgreen", ColorHexCode = "#90EE90", Status = 0 },
			new ColorsList { ColorName = "lightpink", ColorHexCode = "#FFB6C1", Status = 0 },
			new ColorsList { ColorName = "lightsalmon", ColorHexCode = "#FFA07A", Status = 0 },
			new ColorsList { ColorName = "lightseagreen", ColorHexCode = "#20B2AA", Status = 0 },
			new ColorsList { ColorName = "lightskyblue", ColorHexCode = "#87CEFA", Status = 0 },
			new ColorsList { ColorName = "lightslategray", ColorHexCode = "#778899", Status = 0 },
			new ColorsList { ColorName = "lightsteelblue", ColorHexCode = "#B0C4DE", Status = 0 },
			new ColorsList { ColorName = "lightyellow", ColorHexCode = "#FFFFE0", Status = 0 },
			new ColorsList { ColorName = "lime", ColorHexCode = "#00FF00", Status = 0 },
			new ColorsList { ColorName = "limegreen", ColorHexCode = "#32CD32", Status = 0 },
			new ColorsList { ColorName = "linen", ColorHexCode = "#FAF0E6", Status = 0 },
			new ColorsList { ColorName = "magenta", ColorHexCode = "#FF00FF", Status = 0 },
			new ColorsList { ColorName = "maroon", ColorHexCode = "#800000", Status = 0 },
			new ColorsList { ColorName = "mediumaquamarine", ColorHexCode = "#66CDAA", Status = 0 },
			new ColorsList { ColorName = "mediumblue", ColorHexCode = "#0000CD", Status = 0 },
			new ColorsList { ColorName = "mediumorchid", ColorHexCode = "#BA55D3", Status = 0 },
			new ColorsList { ColorName = "mediumpurple", ColorHexCode = "#9370DB", Status = 0 },
			new ColorsList { ColorName = "mediumseagreen", ColorHexCode = "#3CB371", Status = 0 },
			new ColorsList { ColorName = "mediumslateblue", ColorHexCode = "#7B68EE", Status = 0 },
			new ColorsList { ColorName = "mediumspringgreen", ColorHexCode = "#00FA9A", Status = 0 },
			new ColorsList { ColorName = "mediumturquoise", ColorHexCode = "#48D1CC", Status = 0 },
			new ColorsList { ColorName = "mediumvioletred", ColorHexCode = "#C71585", Status = 0 },
			new ColorsList { ColorName = "midnightblue", ColorHexCode = "#191970", Status = 0 },
			new ColorsList { ColorName = "mintcream", ColorHexCode = "#F5FFFA", Status = 0 },
			new ColorsList { ColorName = "mistyrose", ColorHexCode = "#FFE4E1", Status = 0 },
			new ColorsList { ColorName = "moccasin", ColorHexCode = "#FFE4B5", Status = 0 },
			new ColorsList { ColorName = "navajowhite", ColorHexCode = "#FFDEAD", Status = 0 },
			new ColorsList { ColorName = "navy", ColorHexCode = "#000080", Status = 0 },
			new ColorsList { ColorName = "oldlace", ColorHexCode = "#FDF5E6", Status = 0 },
			new ColorsList { ColorName = "olive", ColorHexCode = "#808000", Status = 0 },
			new ColorsList { ColorName = "olivedrab", ColorHexCode = "#6B8E23", Status = 0 },
			new ColorsList { ColorName = "orange", ColorHexCode = "#FFA500", Status = 0 },
			new ColorsList { ColorName = "orangered", ColorHexCode = "#FF4500", Status = 0 },
			new ColorsList { ColorName = "orchid", ColorHexCode = "#DA70D6", Status = 0 },
			new ColorsList { ColorName = "palegoldenrod", ColorHexCode = "#EEE8AA", Status = 0 },
			new ColorsList { ColorName = "palegreen", ColorHexCode = "#98FB98", Status = 0 },
			new ColorsList { ColorName = "paleturquoise", ColorHexCode = "#AFEEEE", Status = 0 },
			new ColorsList { ColorName = "palevioletred", ColorHexCode = "#DB7093", Status = 0 },
			new ColorsList { ColorName = "papayawhip", ColorHexCode = "#FFEFD5", Status = 0 },
			new ColorsList { ColorName = "peachpuff", ColorHexCode = "#FFDAB9", Status = 0 },
			new ColorsList { ColorName = "peru", ColorHexCode = "#CD853F", Status = 0 },
			new ColorsList { ColorName = "pink", ColorHexCode = "#FFC0CB", Status = 0 },
			new ColorsList { ColorName = "plum", ColorHexCode = "#DDA0DD", Status = 0 },
			new ColorsList { ColorName = "powderblue", ColorHexCode = "#B0E0E6", Status = 0 },
			new ColorsList { ColorName = "purple", ColorHexCode = "#800080", Status = 0 },
			new ColorsList { ColorName = "red", ColorHexCode = "#FF0000", Status = 0 },
			new ColorsList { ColorName = "rosybrown", ColorHexCode = "#BC8F8F", Status = 0 },
			new ColorsList { ColorName = "royalblue", ColorHexCode = "#4169E1", Status = 0 },
			new ColorsList { ColorName = "saddlebrown", ColorHexCode = "#8B4513", Status = 0 },
			new ColorsList { ColorName = "salmon", ColorHexCode = "#FA8072", Status = 0 },
			new ColorsList { ColorName = "sandybrown", ColorHexCode = "#F4A460", Status = 0 },
			new ColorsList { ColorName = "seagreen", ColorHexCode = "#2E8B57", Status = 0 },
			new ColorsList { ColorName = "seashell", ColorHexCode = "#FFF5EE", Status = 0 },
			new ColorsList { ColorName = "sienna", ColorHexCode = "#A0522D", Status = 0 },
			new ColorsList { ColorName = "silver", ColorHexCode = "#C0C0C0", Status = 0 },
			new ColorsList { ColorName = "skyblue", ColorHexCode = "#87CEEB", Status = 0 },
			new ColorsList { ColorName = "slateblue", ColorHexCode = "#6A5ACD", Status = 0 },
			new ColorsList { ColorName = "slategray", ColorHexCode = "#708090", Status = 0 },
			new ColorsList { ColorName = "snow", ColorHexCode = "#FFFAFA", Status = 0 },
			new ColorsList { ColorName = "springgreen", ColorHexCode = "#00FF7F", Status = 0 },
			new ColorsList { ColorName = "steelblue", ColorHexCode = "#4682B4", Status = 0 },
			new ColorsList { ColorName = "tan", ColorHexCode = "#D2B48C", Status = 0 },
			new ColorsList { ColorName = "teal", ColorHexCode = "#008080", Status = 0 },
			new ColorsList { ColorName = "thistle", ColorHexCode = "#D8BFD8", Status = 0 },
			new ColorsList { ColorName = "tomato", ColorHexCode = "#FF6347", Status = 0 },
			new ColorsList { ColorName = "turquoise", ColorHexCode = "#40E0D0", Status = 0 },
			new ColorsList { ColorName = "violet", ColorHexCode = "#EE82EE", Status = 0 },
			new ColorsList { ColorName = "wheat", ColorHexCode = "#F5DEB3", Status = 0 },
			new ColorsList { ColorName = "white", ColorHexCode = "#FFFFFF", Status = 0 },
			new ColorsList { ColorName = "whitesmoke", ColorHexCode = "#F5F5F5", Status = 0 },
			new ColorsList { ColorName = "yellow", ColorHexCode = "#FFFF00", Status = 0 },
			new ColorsList { ColorName = "yellowgreen", ColorHexCode = "#9ACD32", Status = 0 }
		};
		}
	}
}
